### ISSUE TITLE
When someone uploads a file to through an upload workflow they can't delete the file and start over. Can we look at the box widget and see if we can add a remove file after it's been uploaded?

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrackCarmony** [comment]
Sam, 
here's the endpoint that you can hit that will remove the file as well as the connection from the field.

DELETE /api/box/file/:file_id
