### ISSUE TITLE
President and Secretary Validation on Corporate Organizational Documents

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#104]
If there is another title like CEO in front of President and Secretary it bugs out and says they still need to specify a president and secretary.

**Comment by danielandelin** [comment]
[{"type":"RegExp","validator":"\\\"Title\\(s\\)\\\":\\\"(\\|)?President","message":"Must select someone to serve as the President"},{"type":"RegExp","validator":"\\\"Title\\(s\\)\\\":\\\"[^\\\"]*Secretary","message":"Must select someone to serve as the Secretary (This is a corporate secretary, not a receptionist or assistant. This should be one of your founders. The president may also serve as secretary.)"}]

**Comment by BrackCarmony** [comment]
Updated validator to this. 
```
[
   {
      "type": "RegExp",
      "validator": "\\\"Title\\(s\\)\\\":\\\"([^\\\"\\|]*\\|)*President",
      "message": "Must select someone to serve as the President"
   },
   {
      "type": "RegExp",
      "validator": "\\\"Title\\(s\\)\\\":\\\"[^\\\"]*Secretary",
      "message": "Must select someone to serve as the Secretary (This is a corporate secretary, not a receptionist or assistant. This should be one of your founders. The president may also serve as secretary.)"
   }
]
```
Okay really this but come on, you know the thing man.
```
[{"type":"RegExp","validator":"\\\"Title\\(s\\)\\\":\\\"([^\\\"\\|]*\\|)*President","message":"Must select someone to serve as the President"},{"type":"RegExp","validator":"\\\"Title\\(s\\)\\\":\\\"[^\\\"]*Secretary","message":"Must select someone to serve as the Secretary (This is a corporate secretary, not a receptionist or assistant. This should be one of your founders. The president may also serve as secretary.)"}]
```
