### ISSUE TITLE
"Must select someone to serve as president" Error even when a president is selected. 

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#109]
![image](https://user-images.githubusercontent.com/68620849/124961314-87414b80-dfda-11eb-9ec5-46858cc5c124.png)

If you put the president as the first title it works but not if the title is after any other title.

**Comment by BrackCarmony** [comment]
Updated validator to this monstrosity should find the President in any position, but not allow vice president to count.

[
   {
      "type": "RegExp",
      "validator": "\\\"Title\\(s\\)\\\":\\\"([^\\\"\\|]*\\|)*President",
      "message": "Must select someone to serve as the President"
   },
   {
      "type": "RegExp",
      "validator": "\\\"Title\\(s\\)\\\":\\\"[^\\\"]*Secretary",
      "message": "Must select someone to serve as the Secretary (This is a corporate secretary, not a receptionist or assistant. This should be one of your founders. The president may also serve as secretary.)"
   }
]
