### ISSUE TITLE
Unable to make a partner group cover document credits

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#158]
https://staging.admin.savvi.legal/#/Partner

Can't get this toggle to work. If I select it and then save the partner group it doesn't stay selected or do what it's supposed to.
![image](https://user-images.githubusercontent.com/68620849/153482645-40320777-d836-4649-b0c8-42713910e243.png)

**Comment by wmerfalen** [comment]
Fix for this is in code review. Will push to prod as soon as it's approved
