### ISSUE TITLE
Document Completion Email Update

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#161]
![image (1)](https://user-images.githubusercontent.com/68620849/154771646-ead9a6f8-5c4f-48f8-8c2d-e4ef153515f9.png)

Everyone has signed Hero, Inc.--Board Consent (Equity Grant) Dec 29th, 2021. Here is your copy of the signed document.

We should update this to say something like: - "Hero, Inc.--Board Consent (Equity Grant) Dec 29th, 2021" has been completed. A copy of the signed agreement is attached.

**Comment by wmerfalen** [comment]
A PR for this is waiting to be approved.
