### ISSUE TITLE
Resources Created in Draft State from Standing Forms

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#162]
When a standing form is started it creates a resource for the person filling out the form. How does that resource go from being "Is Draft" to a visible resource on the company's account? 

Suggesting that when the associated task that has been created for that resource is submitted it becomes a full resource on the account.

![image (2)](https://user-images.githubusercontent.com/68620849/154775016-eb85c822-4d2c-46d6-8a6b-6e0054e832af.png)

**Comment by danielandelin** [comment]
This is still an issue.

**Comment by wmerfalen** [comment]
https://github.com/savvi-legal/server/pull/494#pullrequestreview-930779948

**Comment by wmerfalen** [comment]
The fix has been pushed to all environments. Closing.
