### ISSUE TITLE
When documents are sent automatically, have to manually refresh for updated status.

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#164]
# What URL?
https://demo.savvi.legal/c/368/workbench/tasks/5487/13124/task-view

Sent documents automatically, after the documents sent, the status returned as "email not sent". Had to manually refresh in order to return the status "not signed".

**Comment by SHRoberts91** [comment]
Added a fix that works for now, where after the initial finalize and 'loading' of the document I'm calling the task again at which point the status is updated correctly, so I'll mark this as closed. 

But I'll share the bug in case we need to reference it later and want to actually fix it. How to recreate: 
- When the document is generated a 'Document Signature Links Generated' timeline is created for that subtask(transaction.tasks[]).
- This fires off the `refresh_timeline` socket, which informs me that the timeline in the Task view is updated so I should hit `GET /account/transaction/${transactionId}`.
- For whatever reason the status on that subtask isn't updated to 'Awaiting Signature' yet, but if I were to refresh the page right away it would be
- This is probably somewhere a settimeout was delaying something even by a few hundred milliseconds.
- Relative path to that property: `transaction.tasks[0].state`.

**Comment by SHRoberts91** [comment]
Added a fix that works for now, where after the initial finalize and 'loading' of the document I'm calling the task again at which point the status is updated correctly, so I'll mark this as closed. 

But I'll share the bug in case we need to reference it later and want to actually fix it. How to recreate: 
- When the document is generated a 'Document Signature Links Generated' timeline is created for that subtask(transaction.tasks[]).
- This fires off the `refresh_timeline` socket, which informs me that the timeline in the Task view is updated so I should hit `GET /account/transaction/${transactionId}`.
- For whatever reason the status on that subtask isn't updated to 'Awaiting Signature' yet, but if I were to refresh the page right away it would be
- This is probably somewhere a settimeout was delaying something even by a few hundred milliseconds.
- Relative path to that property: `transaction.tasks[0].state`.
