### ISSUE TITLE
Certain emails are failing to send

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#169]
Specifically it seems like when an email has multiple attachments or is an email that is a little bigger.

This one failed to send - 
![image](https://user-images.githubusercontent.com/68620849/155611501-dfabc0d0-fedb-485e-adbf-559803d0e15c.png)

**Comment by coolaj86** [comment]
@danielandelin Is this still an issue?

**Comment by danielandelin** [comment]
@coolaj86 Yes unless a fix has been pushed for it.

**Comment by danielandelin** [comment]
This is definitely still a problem. This is a bug that is causing issues with our customers.

**Comment by SHRoberts91** [comment]
Not an easy way to test this live, but it is working on staging and should be working on live. We'll close for now but keep an eye on it to see if this issue pops up again.
