### ISSUE TITLE
When Accessing a company account through the admin portal unable to set a different user as the owner.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#173]
![image](https://user-images.githubusercontent.com/68620849/156034377-4bd08acc-cba3-46e6-b53a-982f156f807d.png)

**Comment by BrackCarmony** [comment]
Would probably be easier to make it editable on the admin portal than to make it work through possession where auth is more of an issue.

**Comment by danielandelin** [comment]
Yeah that would be even better.

**Comment by SHRoberts91** [comment]
This has been added to the admin portal. closing, @wmerfalen can you reference the admin/server PR's this is fixed in?
