### ISSUE TITLE
Shared Forms are not successfully generating

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#174]
I'm able to go through the process to initiate a shared form and receive a green confirmation notification that the shared form has been generated. But I cannot find any evidence of the shared form on that workflow, even after refreshing. No email has been sent to the recipient of the shared form.

Replicated issue with multiple forms on both live and demo.

Not a same-day bug because this feature isn't currently being emphasized in the UI, but I would recommend a fix for the next development cycle.

**Comment by SHRoberts91** [comment]
This was a bug on the front end, they were being created and connected, they just weren't showing up correctly, should be fixed now.
