### ISSUE TITLE
Add multiple bank accounts via Plaid

### ISSUE THREAD

**Issue by ddbaker1121** [savvi-legal/feedback#178]
Currently, the app removes the option to add a bank via Plaid when one bank account has been connected. In some cases, our customers would like to add multiple bank accounts - specifically our customers making SPVs. 

- [ ] Let's also de-capitalize "via" for the Plaid button. - Matt

**Comment by matthewjrob** [comment]
Let's also de-capitalize "via" for the Plaid button.

**Comment by matthewjrob** [comment]
@ddbaker1121 let's discuss this in our next touchpoint.
