### ISSUE TITLE
[bug] Re-opened and submitted a standing form, but data did not update.

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#186]
# What URL?

(https://app.savvi.legal/data-room/hhPakg7KllKz4PhJWPxyew00/outside-form/hhPakg7KllKz4PhJWPxyew00)

# What were you trying to do? What broke?

I re-opened the Allocation Request Setup form for the "Allocation Request for Series LLC Subscription" project. This form is what generates both the project room and standing form link for this project. After re-submitting with an updated "minimum investment" amount ($1K), the new amount is showing up in the information section under "Financing Information", but the standing form is still displaying the old amount ($5K) under the Review Information section in that view. See screenshot.
<img width="1341" alt="Screen Shot 2022-03-07 at 12 06 16 PM" src="https://user-images.githubusercontent.com/67928291/157101184-57035171-8db8-43a5-82fe-cb5ba96e69c1.png">

**Comment by SHRoberts91** [comment]
I attempted to recreate and was not able to, are you able to recreate it?

**Comment by coolaj86** [comment]
Brack says the DUPLICATE ROW error has been handled (ignored).
