### ISSUE TITLE
Workspaces (Company Select) Sorting Logic (quick fix)

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#191]
Currently all workspaces are sorted by create date, even if the user is just a partner on the account. This makes it clunky for users who are in partner groups to be able to see their accounts where they are an actual owner or admin. I'd recommend that we implement either a default sorting parameter that brings the owner/admin role above the partner role, or else creating two separate tables, one for owner/admin workspaces, and another for connected accounts. We will be doing a more holistic update for this layer this year, so just looking for a quick fix in the meantime.

**Comment by SHRoberts91** [comment]
What we ended up with on Scoping is to have default sorting go by earliest created at and to group partner companies together.
