### ISSUE TITLE
bug: email typo, minor adjustments

### ISSUE THREAD

**Issue by SHRoberts91** [savvi-legal/feedback#193]
The email I got was from staging, assume it's on demo and live as well. 

Main requests:
1. Number doesn't look to match amount of documents needing signed.
2. change to document(s)
3. remove 2nd 'sign'
4. change to document(s)
5. Call to Action looks weird with long document names. I'd say have document name to the left with a call to action button to the right saying 'View Document' or something like that.

<img width="1245" alt="Screen Shot 2022-03-10 at 12 45 15 PM" src="https://user-images.githubusercontent.com/16089848/157743383-8d5f75f9-5bb9-4696-b392-ecac5785b77e.png">

### How do we Reproduce it?

Finalize a Non-Compete Task from the 'Onboard Employees' workflow.

**Comment by SHRoberts91** [comment]
Similar email issue:
- https://github.com/savvi-legal/feedback/issues/187

**Comment by matthewjrob** [comment]
duplicate issue with thoughts from me here: https://github.com/savvi-legal/feedback/issues/203

**Comment by wmerfalen** [comment]
Fix pushed to live. Closing.
