### ISSUE TITLE
Ability to change/remove the owner of an account on the admin portal

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#195]
I often get requests to remove an user from an account since they've left the company and make another user the owner. I'm unable to do this.

![image](https://user-images.githubusercontent.com/68620849/158230468-387a9aeb-b452-4923-8733-d2ca17c61baa.png)

**Comment by SHRoberts91** [comment]
What we need is either an option on the admin portal for this to be changed, or when someone possesses an owner account. Whatever's easiest initially.

**Comment by SHRoberts91** [comment]
Let's go ahead and allow them to change the owner in the admin portal @wmerfalen 
A few things to get you going:
- The best place to add it: The default screen when you log in (https://staging.admin.savvi.legal/#/Data)
- Select a company then hit that down arrow (circled on image)
- probably put the option 'Set as Owner' next to non-owner users (underlined on image)
- Changes previous owner to admin
- *BONUS* Have the option to remove users admins from the company (maybe a trash icon next to the name with a window alert making sure they want to remove that user from the company)
<img width="1672" alt="Screen Shot 2022-03-25 at 11 06 47 AM" src="https://user-images.githubusercontent.com/16089848/160168434-185b73b1-fc0d-4ae8-9a86-aee7145cbb3b.png">

**Comment by coolaj86** [comment]
@wmerfalen This is marked as done on the project board. I see merges, so I'm closing this.
