### ISSUE TITLE
Admin Portal Bug - Unable to add new members to partner groups unless they already have a user account

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#197]
![image](https://user-images.githubusercontent.com/68620849/158274871-bd41c538-0dba-43fd-9ea6-2c67f27ed2ee.png)

Can't add them unless they already have a user account.

**Comment by wmerfalen** [comment]
I'm unsure if this was working at one point and the code was modified unintentionally to prevent it, but currently it doesn't work.

**Comment by wmerfalen** [comment]
Frontend vue component PR: https://github.com/savvi-legal/admin/pull/11/files

**Comment by wmerfalen** [comment]
This has been pushed to production and staging. If you still experience issues, open a new task and tag me.
