### ISSUE TITLE
Carta Report - Admin Portal

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#199]
Getting a bug where the carta export stuff doesn't load.
![image](https://user-images.githubusercontent.com/68620849/158699585-0939cf50-63c8-467c-98b6-6cc9286ace31.png)

**Comment by danielandelin** [comment]
Steps to reproduce

1. Go to https://staging.admin.savvi.legal/#/CartaData - or on live
2. Select an Account
3. If account doesn't have equity grant data page will load. If account has equity grant date page will fail to load.

**Comment by SHRoberts91** [comment]
Error code from staging: `#V42Na5dW`

**Comment by wmerfalen** [comment]
A fix for this is in review. Will get it deployed ASAP.

**Comment by wmerfalen** [comment]
Fix has been deployed to production earlier today. Please reopen this task if you experience any issues.
