### ISSUE TITLE
Email Notifications subject for sent documents

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#203]
When someone is sent a document from Savvi, the subject line says "You have 1 documents on Savvi to review". If we're going to reference the number in the subject line, we want to get it right. It appears that today, even if they have multiple documents waiting for review and signature, the email subject will still show 1. 

My recommendation is that we either update the subject line to say "you have documents on Savvi to review", or else ensure that the variable token is working correctly to reflect the total amount of documents, which would be great. If we do that, I'd recommend the "You have (x) document(s) on Savvi to review", note the parentheses that make the sentence work for single documents.

<img width="1156" alt="Screen Shot 2022-03-21 at 11 53 28 AM" src="https://user-images.githubusercontent.com/67928291/159334409-1974d864-1447-452b-91f3-c36eb9e34f4c.png">

**Comment by SHRoberts91** [comment]
@matthewjrob  Duplicate of #193

**Comment by matthewjrob** [comment]
@SHRoberts91 Ok, closing then. Feel free to link to this on the other one if it's useful.
