### ISSUE TITLE
PandaDoc Variable Number of Signatories not being removed on document generation

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#205]
Steps to recreate:

1. Issue Equity Workflow - Generate Issuance
2. Generate Equity Board Consent Document

Here's a live example:
Company:
DA's Test Account

Equity Board Consent Task:
https://app.savvi.legal/c/8/workbench/9/11229/24413/task-view

PandaDoc:
https://app.pandadoc.com/p/edfa25fbdbc2cbaa4a771d22178ef77a7fc0d0d7?

**Comment by SHRoberts91** [comment]
This is occurring on Staging as well for easier testing @BrackCarmony .

**Comment by BrackCarmony** [comment]
Fixed by 
https://github.com/savvi-legal/server/pull/466
