### ISSUE TITLE
Deal Room did not update after task re-submission

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#208]
Submitted a Subscription Agreement task and generated a deal room, then re-opened the task and made changes to both company and purchaser signatory fields. The deal room didn't accurately reflect the changes that were submitted. Interestingly it showed the original company signatory that had been added as well as the new signatory that was added.  Did not show the new purchaser signatory, still showed the original one.

**Comment by SHRoberts91** [comment]
Test

**Comment by SHRoberts91** [comment]
#208
