### ISSUE TITLE
Can't Move Room Documents

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#209]
When I move a document in a room, I get a green verification, but the doc doesn't actually move.

**Comment by SHRoberts91** [comment]
Steps to recreate on staging:
1. Log in to services@savvi.legal
2. select 'Mode Inc.' company.
3. go to https://staging.savvi.legal/data-room/sva_GgU9fgjWtLW8iEJkl4yqkQ
4. When in edit mode, the documents have up and down arrow to sort them.
5. When you try to sort, hits endpoint and comes back success (`200 PATCH https://staging.savvi.legal/api/account/room/document/swap/608/607`) But doesn't actually work.

To reference a similar endpoint that is working you can check out the room link swap: `PATCH https://staging.savvi.legal/api/account/room/link/swap/52/53`

**Comment by wmerfalen** [comment]
We figured out this is an issue for the frontend code. I have since stopped working on this as the backend code does seem to be working correctly.
