### ISSUE TITLE
Website: SPV Pricing Updates

### ISSUE THREAD

**Issue by ddbaker1121** [savvi-legal/feedback#210]
We'd like to make changes to the SPV pricing page as follows:

SPV Formation (a la carte)
- Same features
- Change pricing to $4,000/SPV
- Change CTA: "Talk to Sales"

Syndicate Management
- Change name to "Syndicate Portfolio Management"
- Same features
- Change pricing to "Starting at $2,400/SPV"

Add-on Services
- Keep the same

**Comment by matthewjrob** [comment]
Self-Serve SPVs

-Entity Creation
-Subscription Agreement Automation
-Allocation Request Forms
-Accredited Investor Certification & W9s
-K1 No-Profit Reporting
-Onboarding Call + Chat Support

Pricing: No change
CTA: Talk to Sales

Full-Service SPVs

-Includes Everything in Self-Serve SPVs
-Banking & Wire Management
-K1 Liquidation Filing & Distribution
-Profit Distributions
-Zoom Support

"Starting at $2,000 per SPV"

Add-on Services
-SPV Liquidation Admin
-Counsel & Document Drafting
-KYC & AML Compliance
-Blue Sky Filings & Edgar Codes
-Custom Forms & Templates
-Crowdfunding Vehicles
