### ISSUE TITLE
Task Status - UI is messed up if title of process is too long

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#212]
Says Filing here instead of "Ready for Filing"
![image](https://user-images.githubusercontent.com/68620849/160718691-1ee19960-4ad4-4d2a-95a0-5e2c0bd4690a.png)

**Comment by danielandelin** [comment]
How it should look - 
![image](https://user-images.githubusercontent.com/68620849/160718818-f4c30ef3-77b6-4949-aff7-372885d8b514.png)

**Comment by danielandelin** [comment]
after looking into this more - I believe the status updates are being triggered when a ticket is moved in hubspot - this is pretty cool but wondering if we just want to have three set statuses - when it hasn't been submitted - Incomplete, after it has been submitted - Awaiting Review, and then Completed. Not sure what we want to do.

**Comment by danielandelin** [comment]
Also just realized it's because the name of the process is longer than all the others that it's pushing the text over

**Comment by SHRoberts91** [comment]
fix pushed with https://github.com/savvi-legal/app/pull/396.
