### ISSUE TITLE
getting rid of option to delete payment method

### ISSUE THREAD

**Issue by heapies1** [savvi-legal/feedback#213]
It might be interesting to give users only an option to update their payment method rather than outright deleting it. I feel like we’ve had some people delete their payment method to avoid being charged rather than cancelling but this would prevent that from happening and have them reach out to us if they’d like to make changes to their subscription.

**Comment by SHRoberts91** [comment]
I've pushed a fix for this, I'll go ahead and link the pr and get this closed.
