### ISSUE TITLE
Creating New Users Accounts.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#215]
demo.savvi.legal/register

![image](https://user-images.githubusercontent.com/68620849/160905799-833bc939-2a8b-46d8-b3c5-374d49041b34.png)

**Comment by coolaj86** [comment]
Looks like demo just hadn't restarted with the last push.

I would like to know _why_ it didn't restart - because there is an unresolved problem there - but I don't have enough info to trace that, and it's working now.
