### ISSUE TITLE
Document View - Remove Documents with a status of deleted.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#217]
need to filter out all deleted documents from the documents view.

![image](https://user-images.githubusercontent.com/68620849/161128607-4f180c99-c030-4dfe-9f86-0243eef41604.png)

**Comment by SHRoberts91** [comment]
Currently this is a fix on my end, we can look into filtering that data on the backend, but for now I'll get a fix up for this.

**Comment by wmerfalen** [comment]
I will be following up with @SHRoberts91 about this and verify if a fix has been deployed to any environment.

**Comment by wmerfalen** [comment]
Approved the PR by @SHRoberts91. Deployment likely to happen before EOD today (2022-04-04).
