### ISSUE TITLE
Hubspot ticket being created for a task that we don't want one being created

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#219]
Persistent Forms are a new task type. Some task types create hubspot tickets and others don't. We need to set this type to not create tickets.

https://app.hubspot.com/contacts/4660402/ticket/854303763/

**Comment by danielandelin** [comment]
It's also creating tickets on live for Assessments for some reason. @wmerfalen

**Comment by wmerfalen** [comment]
The fix for this is live. Let us know if this is still an issue.
