### ISSUE TITLE
Shared Form Email Not Sending

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#234]
When sharing a form for a non-admin user to fill out part of a questionnaire in a workflow the email isn't sending to the person who is supposed to fill it out.

1. Onboard Contractor Workflow
2. Select Generate and a Independent Contractor Agreement
3. Click Share form from the additional options button - 
![image](https://user-images.githubusercontent.com/68620849/168678378-07852a77-3d35-4d8b-b6c2-5a2f0553d2be.png)

Email is supposed to send but it is not sending.

**Comment by SHRoberts91** [comment]
The endpoint getting hit for that shared form that we'll most likely want to look into is `api/account/transaction/:transaction_id/outside` with `send_email: true` in the body.

**Comment by wmerfalen** [comment]
looking into this

**Comment by wmerfalen** [comment]
fix was pushed to staging and prod
