### ISSUE TITLE
Sending new tickets to multiple different pipelines on hubspot

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#235]
@BrackCarmony Let's chat about this when you get a minute.

**Comment by BrackCarmony** [comment]
If we don't need the second ticket to be in control of wether the task is closed or not, we could add a hubspot ticket event similar to the send email event.  If we want to do something more complicated where both tickets need to make it to a terminal bucket before the ticket is closed out that'll be a bit trickier to make happen.

**Comment by BrackCarmony** [comment]
The other benefit of making it a task would be it could have conditional logic for it to create the extra ticket.
