### ISSUE TITLE
Granting advanced subscription Access through Partner Group it should also be granting starter access.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#236]
Connect an account to a partner group that grants an advanced subscription - Use partner code advanced. Go to a workflow that requires a starter subscription - bank account setup. the banner that says you need to upgrade to starter shows up.

**Comment by wmerfalen** [comment]
@danielandelin can you give me an example of this on staging? if not, please let me know which account i can try this on in the production environment
