### ISSUE TITLE
Mislabeling of documents in the Documents view.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#237]
https://app.savvi.legal/c/419/documents

Not sure where all this is happening. Found this example on Savvi Technologies, Inc.

SAFEs are being called Employment Offer Letters.
![image](https://user-images.githubusercontent.com/68620849/170088256-0a545419-c8bd-45c1-89c0-ef0f3d0781e2.png)

**Comment by wmerfalen** [comment]
@danielandelin it looks like the Question Label is being used for that label
The attached photo isn't the exact account, but it has the same label and shows where the label is coming from
![Screen Shot 2022-05-24 at 11 14 54 AM](https://user-images.githubusercontent.com/2633195/170094121-9b3e1fc3-318a-4648-8386-de9f0cc868e5.png)

**Comment by SHRoberts91** [comment]
So I pushed a fix that will correctly show the label for most of these, the main thing here is that that template label used in the documents section is being pulled from `flat_features` or the `template_variant`, and some of these documents are for whatever reason being connected to an incorrect template variant. I adjusted the logic to show the label from `flat_features` before `template_type` so they'll stop using that incorrect label. 

We will have to look more into all the items in `document_history` that have a `panda_template_id` of `NWGMkzt4R6oH6KP2ibbfgn`

**Comment by SHRoberts91** [comment]
And it looks like there was a dev `template_variant` item with the same `panda_template_id` as the real one, and this was causing the dev one to be pulled by that endpoint, I changed the `panda_template_id` on the dev one and it is no longer doing this 👌
