### ISSUE TITLE
Company Report in Data Room Reports task Showing Another Company from another account!!!

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#238]
If you connect a partner to a company and that partner also has their own account on Savvi the partner group is bringing in the other company into the account.

![image](https://user-images.githubusercontent.com/68620849/170105770-fa7d4fd7-63a4-4dd6-b101-c281936708e4.png)

**Comment by SHRoberts91** [comment]
I've got a frontend bandaid coming through, but we'll want to figure this out on the backend on why two companies are coming through here (`GET /api/account/transaction/:transaction_id/questionnaire`) and in the Reports View (`GET /api/company_info/all`). The Reports View endpoint is probably an easier place to start. You can see the `resourceListData` object (`payload[0].resourceListData`) has the 2 company items, when it should only have one.
