### ISSUE TITLE
Removing lease agreements - Lease Boolean not saving

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#246]
Data Room Setup task
https://staging.savvilegal.dev/c/264/workbench/6/6887/17971/task-view

**Comment by danielandelin** [comment]
I can't deselect this box - 
![image](https://user-images.githubusercontent.com/68620849/173699624-a4424bc8-c359-4741-94fc-544f0943ba1b.png)

**Comment by BrackCarmony** [comment]
Issue seems to have been resolved.  Closing for now.
