### ISSUE TITLE
Email Content update for document/signature request emails

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#256]
Update Subject to say " You have a new document to review."

Update Body to say: 

"Hi Daniel,

Please review and sign the following document(s)."

![image](https://user-images.githubusercontent.com/68620849/180885744-006bee2d-9bc6-44bc-9b0f-800ad8e96d36.png)

**Comment by BrackCarmony** [comment]
https://github.com/savvi-legal/server/pull/702

**Comment by coolaj86** [comment]
So we landed on removing the pluralization?
