### ISSUE TITLE
question required on data room setup

### ISSUE THREAD

**Issue by heapies1** [savvi-legal/feedback#260]
![Screen Shot 2022-08-16 at 09 04 35](https://user-images.githubusercontent.com/102632012/184940203-20bf4db3-5ce2-4c18-9331-8595137baf46.png)
is there suppose to be an asterisk for required questions? All of these are required but it's not showing so. Just a small thing
same on demo and live

**Comment by SHRoberts91** [comment]
Fix going up, the required asterik just wasn't showing up for radio input questions
