### ISSUE TITLE
Remove "Review Information" section from standing forms. 

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#262]
Can we remove it from Standing forms but not from close the loop/outside forms? @SHRoberts91 

https://staging.savvilegal.dev/api/redirect/form/svf_vvkyn953f2chm1nnc1tzzcz0eg

**Comment by SHRoberts91** [comment]
@danielandelin That should be fine. Would we want a property in the future that you can toggle in the admin portal for whether the 'Review Information' shows or doesn't and just have that property automatically default to off for standing forms and on for other outside forms? Or if we'll just always want it not to show for standing forms and show for others then the proposed solution is fine

**Comment by danielandelin** [comment]
Hmm.. I'm fine with either way. For now we can just have it defaulted to off for standing/persistent forms and on for outside forms.

**Comment by SHRoberts91** [comment]
Alright, push going up.
