### ISSUE TITLE
Extra Document Credits Added to Accounts

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#6]
Demo company called Credit Test just had an extra 48 credits added. It didn't add them immediately after I created the subscription on 8/3 but sometime between then and 8/4 it added an extra 48.

to reproduce - sign up for an advanced subscription. might be a timing thing for when a subscription renews.

**Comment by solderjs** [comment]
@BrackCarmony Could you check the database for this? I wonder if it's related to string concatenation with my bugfix.

(substracting `"8" - "4"` would be correct, but `"4" + "8"` would not)

**Comment by danielandelin** [comment]
FYI I'm seeing it on all new accounts now. Not immediately but after a day
or so. It adds an extra 24 or 48 credits depending what subscription they
signed up for.

**Comment by solderjs** [comment]
Hey @danielandelin, @matthewjrob says that this sounds correct for annually billed credits (as opposed to monthly-billed credits).

**Comment by danielandelin** [comment]
No it's double adding the 24 or 48

**Comment by solderjs** [comment]
@BrackCarmony Needs your input, please.

**Comment by solderjs** [comment]
@BrackCarmony Needs your input, please.
